### ISSUE TITLE
[FR] Allow `affix` to be multi-lined

### ISSUE THREAD

**Issue by jaekyeom** [ekickx/clipboard-image.nvim#10]
Hi,
Thanks for this great plugin.

Currently, it looks that the `affix` can only be a single-line string.
However, there are some cases that allowing it to be a multi-line string can be useful e.g. latex.
Maybe could this be implemented, please?

**Comment by ekickx** [comment]
Ah that's a good idea. Lua allow multi-line string with `[[]]` but I think I haven't try it wether it works with my plugin or not.

**Comment by ekickx** [comment]
@jaekyeom  Which behavior do you prefer?

```lua
-- Before
line 1|
-- After
line 1 pasted_image|
```
or
```lua
-- Before
line 1|
-- After
line 1|
pasted_image
```

**Comment by jaekyeom** [comment]
Wow, thanks for looking into it.

I myself find the former more expected.

Also, considering the indentations, I personally think that maybe it should work like pasting?

**Comment by ekickx** [comment]
@jaekyeom Can you try it on [this branch](https://github.com/ekickx/clipboard-image.nvim/tree/feat_multiline_support)?

If you want to paste something like:
```
{
  pasted_image
}
```

Your config can be:

```
require'clipboard-image'.setup {
  default = {
    affix = "{\n  %s\n}"
  },
}
```

or

```
require'clipboard-image'.setup {
  default = {
    affix = [[{
  %s
}]]
  },
}
```

**Comment by jaekyeom** [comment]
@ekickx I've just tried it, and it works really nicely!
(It prints the debug messages, but I guess you put it in on purpose.)
Thank you so much.

**Comment by ekickx** [comment]
Oh God I forgot to remove that 😆

**Comment by ekickx** [comment]
@jaekyeom I have merged it into `main` now
