### ISSUE TITLE
Create img_dir at the same level as this file 

### ISSUE THREAD

**Issue by KoryChiu** [ekickx/clipboard-image.nvim#24]
Hi there ,

I often edit a file in other directory , is it possible create img_dir at the same level as the file ?

As the below situation , I wanna $img_dir in the /wiki/work/img/ not in the wiki/img/

Please make this proposal a new feature 🙏 🥰
```
tree .
│   ├── wiki
│   │   ├── school
│   │   ├── work
│   │   ├── personal


cd wiki
vim work/2022-01-01.md
```

**Comment by ekickx** [comment]
You can try this
```lua
img_dir = {"%:p:h", "img"}
```

`%:p:h` will get the directory of your current file

**Comment by KoryChiu** [comment]
1) mkdir test1
2) vi test1/hi.md
3) capture a screenshot to clipboard
4) `Esc` and `:PasteImg` 
5) `:wq`
6) tree .
```
tree                                                                                                              ─╯
.
├── test1
│   └── hi.md
└── img
    └── 2022-01-06-18-40-56.png
```

but, I wanna the img folder is in the `test1/img/2022-01-06-18-40-56.png`

**Comment by ekickx** [comment]
Sorry but have you tried it? Because it should work like this
![](https://user-images.githubusercontent.com/26477782/148643835-c4649f81-ad9e-4f09-a236-0f5180915810.mp4)

**Comment by KoryChiu** [comment]
> Sorry but have you tried it? Because it should work like this
> Clip-image-relative-dir.mp4

Yes , I tried.

My init.vim :
```
Plug 'ekickx/clipboard-image.nvim'
lua << EOF
img_dir = {"%:p:h", "img"}
EOF
```

**Comment by ekickx** [comment]
Ah It's not like that. You should either do this
```
Plug 'ekickx/clipboard-image.nvim'
lua << EOF
require'clipboard-image'.setup {
  default = {
    img_dir = {"%:p:h", "img"}
  }
}
EOF
```
Or this (like in the video):
```
Plug 'ekickx/clipboard-image.nvim'
lua << EOF
require'clipboard-image'.setup {
  markdown = {
    img_dir = {"%:p:h", "img"}
  }
}
EOF
```
![image](https://user-images.githubusercontent.com/26477782/149121397-2f7a138b-03c5-43eb-b979-193118fac4d6.png)
<br>
If you're still confused, you can also read this [config section](https://github.com/ekickx/clipboard-image.nvim#confighttps://github.com/ekickx/clipboard-image.nvim#config) in the readme.

**Comment by KoryChiu** [comment]
I change my config as above and I got wrong message :

![image](https://user-images.githubusercontent.com/12044470/150510587-e89c2642-d6fa-4105-92dd-e6af58c5ac38.png)

Am I missing something?

**Comment by ekickx** [comment]
Ok can you upload your config to a repository. I will try to check it.

**Comment by KoryChiu** [comment]
Thank You.  My neovim configs are in the nvim.zip.

[nvim.zip](https://github.com/ekickx/clipboard-image.nvim/files/7917526/nvim.zip)

**Comment by ekickx** [comment]
Sorry for the late reply. The problem with your config is you try to run the plugin's config before the plugin loaded. So you should place the plugin's config after `call plug#end()`.

Here try this [nvim.zip](https://github.com/ekickx/clipboard-image.nvim/files/7923672/nvim.zip)

**Comment by KoryChiu** [comment]
It works !
Thank you for all your assistance, 😃

**Comment by ekickx** [comment]
You're welcome. Glad it's solved
