### ISSUE TITLE
Not support wsl2

### ISSUE THREAD

**Issue by MerliniKing** [ekickx/clipboard-image.nvim#34]
show error:
platform is not supported

**Comment by ekickx** [comment]
Sorry for the late reply. I actually want to add support for wsl in #21 but I can't test it since I don't have windows in my device. 

I will fix the conflict soon and after that can you try it?

**Comment by ekickx** [comment]
Ok I just fixed the merge conflict. You can test #21 now

Oh if you use packer just do

```lua
use {"ekickx/clipboard-image.nvim", branch = "feat_WSL"}
```

**Comment by MerliniKing** [comment]
I use vim-plug for plugin manager, and I install this branch by `Plug 'ekickx/clipboard-image.nvim', { 'branch': 'feat_WSL' }`
But same error again

**Comment by MerliniKing** [comment]
```
clipboard-image: require("clipboard-image.health").check()
========================================================================
## Checking dependencies
  - ERROR: platform is not supported
```

**Comment by MerliniKing** [comment]
additional info:
when run `uname -a` in wsl, the output is `Linux xxxxxxxx 15 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by MerliniKing** [comment]
and the content of `/proc/version` is `Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Mar 2 00:30:59 UTC 2022`

**Comment by MerliniKing** [comment]
when just run `uname`, the output is `Linux`

**Comment by ekickx** [comment]
Ok just to make sure, can you show me the output of this command

```vimscript
:lua print(vim.inspect(vim.fn.readfile("/proc/version")))
```

**Comment by MerliniKing** [comment]
`{ "Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Mar 2 00:30:59 UTC 2022" }`

**Comment by MerliniKing** [comment]
> Ok just to make sure, can you show me the output of this command
> 
> ```
> :lua print(vim.inspect(vim.fn.readfile("/proc/version")))
> ```

`{ "Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Mar 2 00:30:59 UTC 2022" }`

**Comment by ekickx** [comment]
I just pushed a new change. Can you try it now?

**Comment by MerliniKing** [comment]
> I just pushed a new change. Can you try it now?

It shows `powershell is not installed`, but I already add powershell.exe into PATH.

Maybe need change `powershell` to `powershell.exe`?

**Comment by ekickx** [comment]
Hmm weird 🤔.  In [`check_package_installed`](https://github.com/ekickx/clipboard-image.nvim/blob/4765158395b279bccaa90f05e38ce6f8e44f4747/lua/clipboard-image/health.lua#L23), I use `vim.fn.executable` to check for `powershell.exe`. Maybe you can do

```vimscript
:lua print(vim.fn.executable("powershell.exe"))
```

If the output is not `1` then there is something wrong

**Comment by MerliniKing** [comment]
> Hmm weird 🤔. In [`check_package_installed`](https://github.com/ekickx/clipboard-image.nvim/blob/4765158395b279bccaa90f05e38ce6f8e44f4747/lua/clipboard-image/health.lua#L23), I use `vim.fn.executable` to check for `powershell.exe`. Maybe you can do
> 
> ```
> :lua print(vim.fn.executable("powershell.exe"))
> ```
> 
> If the output is not `1` then there is something wrong

the output is 1

**Comment by MerliniKing** [comment]
Oh, maybe the path is wrong, powershell is ok now

**Comment by ekickx** [comment]
So is it ok now? Tell me if it's still not working

**Comment by MerliniKing** [comment]
It shows `There is no image data in clipboard`

**Comment by ekickx** [comment]
Have you copied the image? If you have and those error still appear than I did something wrong to check the clipboard's content

**Comment by MerliniKing** [comment]
yes, i copied the image in win10, and want to paste in WSL2

**Comment by ekickx** [comment]
Ahh I think I know what's wrong here. I forgot to check clipboard's content on WSL. My bad

**Comment by ekickx** [comment]
Can you try it now?

**Comment by MerliniKing** [comment]
> Can you try it now?

It's OK now！

**Comment by MerliniKing** [comment]
Really thx for your efforts!

**Comment by ekickx** [comment]
You're welcome. And thanks too for helping me fixing this issue. I'll merge #21 now
