### ISSUE TITLE
filetype specific configuration

### ISSUE THREAD

**Issue by jdeut** [ekickx/clipboard-image.nvim#6]
In case nvim is used to write multiple markup languages (html, md, tex) it would help to configure the plugin like this:

```
require'clipboard-image'.setup {
  tex = { 
    img_dir = 'img',
    img_dir_txt = 'img',
    img_name = function () return os.date('%Y-%m-%d-%H-%M-%S') end,
    affix = [[\includegraphics{%s}]]
  },
  md = { 
    img_dir = 'img',
    img_dir_txt = 'img',
    img_name = function () return os.date('%Y-%m-%d-%H-%M-%S') end,
    affix = '![](%s)''
  },
...
}
```

**Comment by ekickx** [comment]
Ohh that's a good idea. I'll find a time to work on it.

**Comment by jdeut** [comment]
> Ohh that's a good idea. I'll find a time to work on it.

Thanks a lot :)

**Comment by ekickx** [comment]
> > Ohh that's a good idea. I'll find a time to work on it.
> 
> Thanks a lot :)

You're welcome (｡•̀ᴗ-)✧
